spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 237056885093-sjorgecogdvog3icouj60pntgbte9di7.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


